import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  holeTransitionContainer: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    gap: 20,
  },
  holeTransitionText: {
    fontSize: 32,
    color: "#333333",
    fontWeight: "400",
    lineHeight: 48, // Increase lineHeight for custom font to prevent clipping
  },
  holeTransitionNumber: {
    fontSize: 72,
    color: "#333333",
    fontWeight: "bold",
    fontFamily: "Slackey_400Regular",
    lineHeight: 80, // Add lineHeight to prevent clipping
  },
  content: {
    flex: 1,
    padding: 20,
    paddingTop: 60,
    backgroundColor: "#FFFFFF",
  },
  scrollContent: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  scrollContentContainer: {
    flexGrow: 1,
    padding: 20,
    paddingTop: 20,
    paddingBottom: 20, // Add bottom padding so content doesn't get clipped
    backgroundColor: "#FFFFFF",
  },
  settingsButton: {
    position: "absolute",
    top: 4,
    right: 4,
    padding: 4,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  settingsButtonText: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#333333",
    letterSpacing: 2,
  },
  bottomButtonContainer: {
    padding: 20,
    // paddingBottom is set dynamically with safe area insets
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
  },
  title: {
    textAlign: "center",
    marginBottom: 30,
    color: "#333333",
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 16,
    marginBottom: 8,
    fontWeight: "600",
    color: "#333333",
  },
  input: {
    borderWidth: 2,
    borderColor: "#85D1DB",
    borderRadius: 8,
    padding: 15,
    fontSize: 18,
    color: "#333333",
    backgroundColor: "#FFFFFF",
  },
  continueButton: {
    backgroundColor: "#B6F2D1",
    padding: 20,
    borderRadius: 12,
    marginTop: 20,
    alignItems: "center",
  },
  continueButtonText: {
    fontSize: 20,
    color: "#333333",
    fontWeight: "bold",
  },
  playerCard: {
    padding: 20,
    marginBottom: 30,
    alignItems: "center",
    marginTop: 0,
  },
  playerName: {
    fontSize: 28,
    color: "#333333",
  },
  holeNumber: {
    fontSize: 16,
    marginTop: 8,
    opacity: 0.7,
    color: "#333333",
  },
  playerStatusContainer: {
    backgroundColor: "#F0F9FF",
    padding: 10,
    borderRadius: 12,
    marginBottom: 12,
  },
  playerStatusTitle: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
    color: "#333333",
    opacity: 0.7,
  },
  playerStatusList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: "space-between",
  },
  playerStatusItem: {
    flexDirection: "row",
    alignItems: "center",
    width: "48%",
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  playerStatusName: {
    fontSize: 13,
    color: "#333333",
  },
  playerStatusActive: {
    fontWeight: "bold",
    color: "#0066CC",
  },
  playerStatusFinished: {
    opacity: 0.5,
    textDecorationLine: "line-through",
  },
  rerollsText: {
    fontSize: 16,
    marginTop: 10,
    opacity: 0.8,
    color: "#333333",
  },
  rollContainer: {
    alignItems: "center",
    marginBottom: 40,
    flex: 1,
    justifyContent: "center",
  },
  rollLabel: {
    fontSize: 20,
    marginBottom: 15,
    color: "#333333",
  },
  rollResult: {
    backgroundColor: "#B3EBF2",
    paddingVertical: 30,
    paddingHorizontal: 40,
    width: "100%",
    alignItems: "center",
    overflow: "hidden",
  },
  rollTextContainer: {
    height: 50,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  slotMachineContainer: {
    height: 28,
    overflow: "hidden",
    width: "100%",
    alignItems: "center",
    position: "relative",
  },
  slotMachineReel: {
    alignItems: "center",
    width: "100%",
  },
  slotMachineItem: {
    height: 28,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    paddingHorizontal: 10,
  },
  nextRollText: {
    position: "absolute",
    top: 50,
  },
  rollText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333333",
    textAlign: "center",
    fontFamily: "Courier",
    lineHeight: 28,
  },
  rollDescription: {
    fontSize: 16,
    color: "#333333",
    opacity: 0.7,
    textAlign: "center",
    marginTop: 12,
    lineHeight: 22,
  },
  buttonContainer: {
    gap: 15,
  },
  gameButton: {
    padding: 20,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  rollButton: {
    backgroundColor: "#85D1DB",
  },
  disabledButton: {
    backgroundColor: "#CCCCCC",
    opacity: 0.5,
  },
  acceptButton: {
    backgroundColor: "#B6F2D1",
  },
  nextHoleButton: {
    backgroundColor: "#FFD166",
  },
  gameButtonText: {
    fontSize: 20,
    color: "#333333",
    fontWeight: "bold",
  },
  progressInfo: {
    marginTop: 30,
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
    backgroundColor: "#C9FDF2",
  },
  progressText: {
    fontSize: 16,
    opacity: 0.7,
    color: "#333333",
  },
  resultCard: {
    padding: 20,
    borderRadius: 16,
    marginBottom: 20,
    borderWidth: 0.5,
    borderColor: "#85D1DB",
    backgroundColor: "#C9FDF2",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  resultPlayerName: {
    marginBottom: 15,
    fontSize: 22,
    color: "#333333",
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#85D1DB",
  },
  statText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333333",
  },
  rerollsSummary: {
    fontSize: 14,
    marginBottom: 10,
    opacity: 0.7,
    color: "#333333",
  },
  resultRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#B3EBF2",
  },
  resultHole: {
    fontSize: 16,
    color: "#333333",
  },
  resultScore: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333333",
  },
  quitButton: {
    marginTop: 15,
    alignSelf: "center",
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  quitButtonText: {
    fontSize: 14,
    color: "#999999",
    opacity: 0.6,
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    zIndex: 9999,
    elevation: 9999,
  },
  modalBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  modalContent: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: "#FFFFFF",
    padding: 30,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#85D1DB",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
  },
  modalTitle: {
    textAlign: "center",
    marginBottom: 15,
    color: "#333333",
  },
  modalMessage: {
    textAlign: "center",
    fontSize: 16,
    marginBottom: 25,
    color: "#666666",
    lineHeight: 22,
  },
  modalButtons: {
    flexDirection: "row",
    gap: 15,
  },
  modalButton: {
    flex: 1,
  },
  modalCancelButton: {
    backgroundColor: "#E0E0E0",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
  },
  modalCancelText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#666666",
  },
  modalQuitButton: {
    backgroundColor: "#FF6B6B",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
  },
  modalQuitText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  playerSelectList: {
    gap: 12,
    width: "100%",
    marginTop: 10,
  },
  playerSelectButton: {
    backgroundColor: "#C9FDF2",
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#85D1DB",
  },
  playerSelectButtonCurrent: {
    borderColor: "#0066CC",
    backgroundColor: "#E6F3FF",
  },
  playerSelectName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333333",
    marginBottom: 4,
  },
  playerSelectThrows: {
    fontSize: 14,
    color: "#666666",
  },
  progressBarContainer: {
    width: "100%",
    marginTop: 20,
    paddingHorizontal: 10,
  },
  progressBarBackground: {
    width: "100%",
    height: 8,
    backgroundColor: "#E0E0E0",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#85D1DB",
    borderRadius: 4,
  },
  // Results page tabs
  tabsWrapper: {
    borderBottomWidth: 2,
    borderBottomColor: "#E0E0E0",
  },
  tabsContainer: {
    flexGrow: 0,
    flexShrink: 0,
  },
  tabsContentContainer: {
    paddingRight: 10,
    paddingTop: 10,
  },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginRight: 8,
    marginBottom: -2,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
    backgroundColor: "transparent",
  },
  tabActive: {
    borderBottomColor: "#85D1DB",
  },
  tabText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#999999",
  },
  tabTextActive: {
    color: "#333333",
    fontWeight: "bold",
  },
  // Summary section
  statsScrollView: {
    flex: 1,
    marginBottom: 20,
    marginTop: 20,
  },
  summaryCard: {
    padding: 16,
    marginBottom: 20,
  },
  summaryTitle: {
    marginBottom: 15,
    color: "#333333",
    fontSize: 20,
  },
  summaryStatsRow: {
    width: "100%",
    gap: 8,
  },
  summaryStatItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  summaryStatLabel: {
    fontSize: 16,
    color: "#333333",
    fontWeight: "500",
  },
  summaryStatValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333333",
  },
  // Hole details
  detailsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
    color: "#333333",
    paddingLeft: 5,
  },
  holeDetailCard: {
    backgroundColor: "#FFFFFF",
    padding: 15,
    borderRadius: 14,
    marginBottom: 12,
    borderWidth: 0.5,
    borderColor: "#E0E0E0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  holeDetailHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  holeDetailTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333333",
  },
  holeDetailScore: {
    fontSize: 16,
    fontWeight: "600",
    color: "#0066CC",
  },
  throwsList: {
    marginTop: 5,
  },
  throwsListTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666666",
    marginBottom: 8,
  },
  throwItem: {
    flexDirection: "row",
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: "#F5F5F5",
    borderRadius: 6,
    marginBottom: 4,
  },
  throwNumber: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#666666",
    width: 30,
  },
  throwResult: {
    fontSize: 14,
    color: "#333333",
    flex: 1,
  },
});
